### ISSUE TITLE
relative path is not working?

### ISSUE THREAD

**Issue by sirech** [MarcoIeni/intelli-space#1]
hi first of all, thanks for the shortcuts. As a `spacemacs` lover, I really like the idea of using that in intellij.

Anyways, I have been trying to make it work and could not make it recognize the bindings. After a lot of trial and error, it seems that switching imports like:

    source ./intelli-space/spacemacs/settings.vim

to

    source ~/intelli-space/spacemacs/settings.vim

fixed my issue. I'm not sure if this a problem with my own setup, but I think it is pretty vanilla, so I'm not sure if this is a general fix or if it is only for me

**Comment by marcoieni** [comment]
I think that with `~` it will not work under windows.

Is your .ideavimrc file into your home directory?

EDIT: I just realized that those paths should not work under windows anyway, because of backslash. I will investigate on this.

**Comment by marcoieni** [comment]
I made the transition to absolute paths as you suggested.
Actually, with relative paths it was not working on Windows and now it is.
Thank you very much! :)
