### ISSUE TITLE
Comma for major mode

### ISSUE THREAD

**Issue by smogstate** [MarcoIeni/intelli-space#11]
Hi, 
i got used to comma to access major mode key bindings. I saw no other way just to copy your files and hardcode it.

The question, do you know any other convinient methods to do so? I am not a vim specialist. Or i can write a script which generate additional package based on major mode files provided.

**Comment by marcoieni** [comment]
One quick solution I found is to add this at the end of your .ideavimrc:
```
nmap , <leader>m
vmap , <leader>m
```

I tried it for a couple of minutes and it works pretty well for me.
It looks like the `,` is expanded only at the beginning of the key binding, so for example if you have some thing like:

```
nnoremap <leader>mr<leader>m      :action RenameElement<CR>
```
the action is triggered if you type `,r<SPC>m` but it doesn't work if you type `,r,` (which is what I would expect).

You can still use the `,` in the middle of other key bindings, for example the following continues to work:
```
nnoremap <leader>a,      :action RenameElement<CR>
```

Let me know if this works for you!
