### ISSUE TITLE
Assign which-key names to all key bindings

### ISSUE THREAD

**Issue by marcoieni** [MarcoIeni/intelli-space#17]
We are working on the branch [which-key](https://github.com/MarcoIeni/intellimacs/tree/which-key) in order to add which-key support to intellimacs.
We have to assign to each key binding the name to be showed in [idea-which-key](https://github.com/TheBlob42/idea-which-key).

You can see the current status of the work in PR #15. This PR is automatically updated once PR against the `which-key` branch are merged.
In order to contribute, leave a comment to tell on which module you want to work and then open a PR against the `which-key` branch where you add the name of the key bindings. For an example, see #16.
As you can see from the examples, modules can be both under `spacemacs` and `extra`.

updated modules:
- [X] applications.vim
- [X] bookmarks.vim
- [X] buffers.vim
- [X] colors.vim
- [X] compile-comments.vim
- [X] errors.vim
- [X] files.vim
- [X] frame.vim
- [X] git-vcs.vim
- [X] help.vim
- [X] help-history.vim
- [X] insertion.vim
- [X] jump.vim
- [X] jump-join-split.vim
- [X] leader.vim
- [X] major mode
- [X] misc.vim
- [X] narrow-numbers.vim
- [X] projects.vim
- [X] quit.vim
- [X] registers-rings-resume.vim
- [X] run.vim
- [X] search.vim
- [X] search-symbol.vim
- [X] text.vim
- [X] toggles.vim
- [X] ui_toogles-themes.vim
- [X] windows.vim
- [X] zoom.vim

If you want to try this follow the instructions of the readme of #15 and do:

```sh
cd ~/.intellimacs
git pull
git checkout which-key
```

P.s. you don't need to be an expert to contribute, you can also edit a file from your browser. Just make sure you are in the [which-key](https://github.com/MarcoIeni/intellimacs/tree/which-key) branch.

**Comment by jmrah** [comment]
Hi @MarcoIeni.  I'm interested in having a stab at  `buffers.vim`  You can go ahead and make a checkbox on that one.

Question about the naming of keybinding values that show up in the which-key menu.  Consider these two keybindings in Spacemacs:

    1) SPC -> b -> b -> list-buffers
    2) SPC -> b -> d -> Kill buffer

Spacemacs often uses snake-case like in 1), but in other places uses the format of 2).  
Do you have any opinion on which format the keybinding descriptions should take in intellimacs?

**Comment by marcoieni** [comment]
Thanks for helping! I am using snake-case everywhere. No reasons in particular.

**Comment by jmrah** [comment]
Understood.  I will follow suit, and use snake-case in my PR.

**Comment by jmrah** [comment]
@MarcoIeni in your original post, you have the zoom.vim checkbox _unchecked_.  I believe this menu was done in PR #28

**Comment by marcoieni** [comment]
Thanks everyone! I will try to release this in the next hours

**Comment by marcoieni** [comment]
Released it!
Run `git pull` inside `.intellimacs` directory to update.
If you experience some issues, open an issue and do `git checkout 8e29374c17caff55c29c973ccf3c8555599a78ed` to go back to the previous version.
