### ISSUE TITLE
Space prefixed hotkeys don't work in tool windows

### ISSUE THREAD

**Issue by lexxish** [MarcoIeni/intelli-space#2]
When tool windows are focused they ignore hotkeys that begin with `<SPACE>` even though other hotkeys work fine.

**Comment by marcoieni** [comment]
Yes, this is a known issue, it is also mentioned in the readme in the tip "Go back to code".
The hotkeys defined in Intellij work fine, but the ones defined in IdeaVim don't. 

Unfortunately, as far as I know, this is not an issue that we can solve.
Maybe the IdeaVim team could do something about it. 

Anyway, as mentioned in the tip, if you press Esc you go back to the editor and you can use IdeaVim key bindings again :)

**Comment by lexxish** [comment]
I opened an issue against IDEA https://youtrack.jetbrains.com/issue/IDEA-218199

**Comment by marcoieni** [comment]
Ok, I close the issue.
Please write here if there are some news :)
