### ISSUE TITLE
The shortcut to open a new terminal/shell opens a new terminal every time.

### ISSUE THREAD

**Issue by jmrah** [MarcoIeni/intelli-space#20]
Observed behavior
Pressing the key combination `SPC -> '` to open a terminal causes a *new* terminal to be opened everytime.

Desired behavior
Should reuse the last open terminal.

Proposed solution:
Change `SPC -> '` from executing the ideavim action `Terminal.OpenInTerminal` to instead executing ideavim action `ActivateTerminalToolWindow`

**Comment by marcoieni** [comment]
Solved in 8366e5a71ffe4813c7c7bdba0065846a7e215c81
It's in the which-key branch, so it's not available in the main branch yet.
I don't want to have merge conflicts, sorry, I hope it's not a problem :)
