### ISSUE TITLE
GotoPreviousError defined twice

### ISSUE THREAD

**Issue by elken** [MarcoIeni/intelli-space#24]
https://github.com/MarcoIeni/intellimacs/blob/main/spacemacs/errors.vim#L5 and https://github.com/MarcoIeni/intellimacs/blob/main/spacemacs/errors.vim#L13

Same action bound to 2 bindings; which one would you want to be correct?

**Comment by marcoieni** [comment]
Two key bindings are defined for the same action. It's normal. Do you see a problem there? Does not work for you?
For which-key something like this would work:
https://github.com/MarcoIeni/intellimacs/blob/56e84916731a9a91c6bb5e8c73e8291af050fa8c/spacemacs/leader.vim#L28-L32

**Comment by elken** [comment]
It just seems redundant 



Get BlueMail for Android

**Comment by marcoieni** [comment]
it's the same in spacemacs
![image](https://user-images.githubusercontent.com/11428655/110589046-257cec00-8176-11eb-9a82-47028d85352a.png)
Closing this, feel free to add other comments if there is something more :)
