### ISSUE TITLE
'Space' + 'number' focuses the respective window

### ISSUE THREAD

**Issue by CollinQuiason** [MarcoIeni/intelli-space#30]
When opening multiple windows, it would be helpful to be able to focus them via keybinds similar to spacemacs. Space + 1 should focus the first window, Space + 2 should focus the second window, Space + 0 should focus the file tree browser, etc

**Comment by marcoieni** [comment]
Is there an action that let you do it?
You can see all actions by typing `:actionlist`

**Comment by CollinQuiason** [comment]
Did a bit of research. This functionality is actually due to an emacs package called 'winum' https://github.com/deb0ch/emacs-winum

There is no action in :actionlist for this specifically, although there is spc + w + h/l to focus left/right windows which should work for my use case

**Comment by marcoieni** [comment]
Ok, so I think for the moment this can't be implemented. Therefore I close the issue.
