### ISSUE TITLE
Alternative installation method

### ISSUE THREAD

**Issue by John0x** [MarcoIeni/intelli-space#44]
Hey, thanks for working on this. It's looking great :)

I was wondering if you could provide a different method of installing the vim configs in future versions. I'm switching between different machines quite frequently and therefore have to keep my .ideavimrc file in sync. That's why it would be awesome to be able to have one big file that I can just add to the end of my .ideavimrc file or something like that. Bundling this as a plugin that can just be installed from within the IDE would of course be the best way, but that's probably not really feasible, is it?

Anyways, keep up the great work 👍

**Comment by marcoieni** [comment]
Thank you so much for your kind words.

So you would like to have just one file with this content?

```
source ~/.intellimacs/spacemacs.vim

" (Optional) Enable other Intellimacs modules
source ~/.intellimacs/extra.vim
source ~/.intellimacs/major.vim
source ~/.intellimacs/hybrid.vim

" (Optional) Enable which-key plugin
source ~/.intellimacs/which-key.vim
```

But at the end you always have to source this file from your .ideavimrc, so you have to write `source ~/.intellimacs/big-file.vim`
What's the difference with sourcing a couple of other files, too?

Furthermore, not everyone would like to have hybrid mode and the which-key plugin is pretty new, so I would like to keep these two things as optional.

> Bundling this as a plugin that can just be installed from within the IDE would of course be the best way, but that's probably not really feasible, is it?

I don't know and honestly I don't have the time to look into it :(

## My approach

By the way to keep files in sync between machines I use [dotfiles](https://wiki.archlinux.org/index.php/Dotfiles).
If you want to keep things simple, you can create a github [gist](https://gist.github.com/) with your own `.ideavimrc` and you download it in every machine you use.

**Comment by John0x** [comment]
I thought of just having one big file that contains everything, so that you can just copy and paste the content of that file into your .ideavimrc
Not as a replacement of the current way but as an addition. 

It would be more comfortable not having to keep the repository on every machine, but I totally understand, that you don't have the time to look into alternative installation methods :)
