### ISSUE TITLE
no popup?

### ISSUE THREAD

**Issue by bommbo** [MarcoIeni/intelli-space#46]
Hi, 
IntelliJ IDEA 2021.2.2-1 (Community Edition)
It's work,But no popup anything?I can use shortcut,but no popup?

**Comment by marcoieni** [comment]
Have you installed https://plugins.jetbrains.com/plugin/15976-which-key/ ?

Do you have `source ~/.intellimacs/which-key.vim` in your .ideavimrc?

**Comment by bommbo** [comment]
Yes,But I don't know how to give you more information.

**Comment by marcoieni** [comment]
Sorry, but for me it's working both in CLion and IntellJ IDEA 2021.2.2 on linux.
![image](https://user-images.githubusercontent.com/11428655/135709864-1894ab26-58dd-4b8b-9f96-e62a1450bb14.png)

I don't know how to reproduce your issue.

Make sure you have pulled the latest version of this repo.

**Comment by bommbo** [comment]
Maybe Community version's problem. It's working for EAP version on linux.
