### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ZackBradshaw** [MarcoIeni/intelli-space#48]
hay I'm trying to get this to work on Rider on windows i have wsl  installed but my ideavimrc is located on my windows partition what do  i need to change to make this work

**Comment by marcoieni** [comment]
Hi, I don't use windows at the moment, so I can't help you a lot. Isn't there a way to create something like a symbolic link, so that you can share the file between the two systems?
Also, this issue is more for https://github.com/JetBrains/ideavim than this repository probably.

**Comment by ZackBradshaw** [comment]
i think the issues is idea vimrc trying to source the linux from windows i have downloaded this to my windows root directory and tryied linking to it with source "C:\intellimacs\spacemacs.vim" but it doesnt work that way either any suggestions

**Comment by ZackBradshaw** [comment]
here is my ideavimrc file i have the intellmacs in both my wls and windows root

**Comment by marcoieni** [comment]
It's not an intellimacs issue from my understanding and I don't know how to reproduce it because I don't have a windows machine, sorry.
