### ISSUE TITLE
not showing 'space + tab' last-buffer keybinding in which-key

### ISSUE THREAD

**Issue by anupam312nwd** [MarcoIeni/intelli-space#51]
Hi, Thanks a lot for creating `intellimacs`. It had made life so easy on `IntelliJ Idea` and `Android Studio` as an emacs user. 
This is a nit pick. The `space + tab` keybinding, where `space` is `leader` key, does not appear in which-key. That is not an issue. The issue is that when I press `space + tab` **fast**, it does move focus to last-buffer, though which-key keeps showing at the bottom of the frame. It does not happen with other keybindings. This is a nit pick as it only makes me pause a bit while moving to last-buffer which I do a lot, but not a functional issue. 
My config: MacBook with M1 chip
Please feel free to close the issue if there is no simple quick-fix.
Thanks!

**Comment by marcoieni** [comment]
Hi! If this is a which-key issue, than it's probably for the plugin https://plugins.jetbrains.com/plugin/15976-which-key

**Comment by anupam312nwd** [comment]
Hi, I am not sure if this is a `which-key` issue or `IdeaVim`. but now that you mention, this does not look like `intellimacs` issue. I am closing this one.

**Comment by stevium** [comment]
@anupam312nwd  I'm also having problems with fast `space + tab` being ignored. Did you manage to find a solution to it?

**Comment by anupam312nwd** [comment]
@stevium I did not find a solution and changed keybinding to a different one.

**Comment by marcoieni** [comment]
Maybe https://glimpse.ieni.dev/docs/troubleshooting#spc-spc-doesnt-work-as-expected-on-mac-os can help
