### ISSUE TITLE
How did you find the `:action X`? 

### ISSUE THREAD

**Issue by IanQS** [MarcoIeni/intelli-space#55]
Hey there! 

I know you're not working on this any longer, so apologies for bothering you. I'm just curious as the

```
nnoremap <leader>mgi    :action GotoImplementation<CR>
vnoremap <leader>mgi    <Esc>:action GotoImplementation<CR>
```

I'm trying to create custom bindings and I'm having issues. Thank you!

**Comment by marcoieni** [comment]
![image](https://github.com/MarcoIeni/intellimacs/assets/11428655/0049f432-5ebb-4cc8-be4a-d9f29f002870)
Hi! Is this what you are looking for?

**Comment by IanQS** [comment]
Yeap! Thank you. So sorry, I forked this and in my own version I deleted there README. 🤦
