### ISSUE TITLE
Recent IdeaVim plugin update breaks intellimacs leader key

### ISSUE THREAD

**Issue by ivanbokii** [MarcoIeni/intelli-space#57]
IdeaVim update v2.8.0, after installation, SPC stops working as a leader key and behaves just as a regular space button. Reverting plugin to 2.7.5 fixes the problem

**Comment by marcoieni** [comment]
I don't have time to look into this. But if somebody figures it out, I'll review and test the PR 👍

**Comment by klochowicz** [comment]
Same here.

 I believe it's related to broken sourcing of external files in the `.ideavimrc`: 

https://youtrack.jetbrains.com/issue/VIM-3273/Config-file-stoped-working

**Comment by marcoieni** [comment]
ok, so it seems the issue is not in intellimacs.

The workaround is to downgrade to IdeaVim 2.7.5 while we wait for a fix on their side.

**Comment by gquittet** [comment]
We can close the issue, the version 2.8.2 released today of IdeaVim is fixing this issue 🎉
