### ISSUE TITLE
Issue with sourcing spacemacs.vim

### ISSUE THREAD

**Issue by SahandJ** [MarcoIeni/intelli-space#60]
I get this when I try to source spacemacs. What am I doing wrong?

![image](https://github.com/MarcoIeni/intellimacs/assets/5606617/b5da7c47-e3ab-4325-9b64-c5285d173a3d)

**Comment by marcoieni** [comment]
Read step 3 of readme carefully.
The source command should be inside the file .ideavimrc

**Comment by SahandJ** [comment]
I have. But unfortunately nothing happens when I hit any keys with vim mode active
